server:
  port: 8150

  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080
        port: 8179

  redis:
    host: localhost
    port: 6379

  session:
    store-type: redis # 整合 spring-session 指定 session 存放到 redis 中

  thymeleaf:
    cache: false #开发模式，关闭缓存
  #服务追踪
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false  #关闭服务发现
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1  #配置采样器
#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
