spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G7XPqnZz1gDJvPXqorc
      secret-key: 6GbTIwcUsXqs5EYb9USUKYXxVUEQqN
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: gmall-s

  application:
    name: guli-third-party

server:
  port: 30000
